# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shadowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShadowUI(object):
    def setupUi(self, ShadowUI):
        ShadowUI.setObjectName("ShadowUI")
        ShadowUI.resize(1168, 751)
        ShadowUI.setMinimumSize(QtCore.QSize(1168, 751))
        ShadowUI.setMaximumSize(QtCore.QSize(1168, 751))
        self.centralwidget = QtWidgets.QWidget(ShadowUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1171, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/Main.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 650, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 85, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(960, 650, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 441, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/Initial.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(620, 20, 256, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparenet;\n"
"boder-radius:none;\n"
"color:white;\n"
"font-size:26px;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(880, 20, 256, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparenet;\n"
"boder-radius:none;\n"
"color:white;\n"
"font-size:26px;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 440, 271, 201))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"text-aline:center;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/shadow.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        ShadowUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShadowUI)
        QtCore.QMetaObject.connectSlotsByName(ShadowUI)

    def retranslateUi(self, ShadowUI):
        _translate = QtCore.QCoreApplication.translate
        ShadowUI.setWindowTitle(_translate("ShadowUI", "MainWindow"))
        self.pushButton.setText(_translate("ShadowUI", "Run"))
        self.pushButton_2.setText(_translate("ShadowUI", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShadowUI = QtWidgets.QMainWindow()
    ui = Ui_ShadowUI()
    ui.setupUi(ShadowUI)
    ShadowUI.show()
    sys.exit(app.exec_())
